logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG
server.port: 8888
spring:
  application:
    name: brewery-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/{application}/